// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxdFvao4Bzv5ZdLDv5R6LQszwOyFIQCvk',
    appId: '1:983675880892:web:756a337828ed4b6847d7b9',
    messagingSenderId: '983675880892',
    projectId: 'ayokesituu',
    authDomain: 'ayokesituu.firebaseapp.com',
    storageBucket: 'ayokesituu.appspot.com',
    measurementId: 'G-44F7F9J0W7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-CxBQ5or2Z4wEw6WGIo6dbb3D4XA04vQ',
    appId: '1:983675880892:android:b949b8bb3e70855247d7b9',
    messagingSenderId: '983675880892',
    projectId: 'ayokesituu',
    storageBucket: 'ayokesituu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvZeotKIGgBTNxSURI4ZOXlpbfaSvpimk',
    appId: '1:983675880892:ios:de3311d77ea14bea47d7b9',
    messagingSenderId: '983675880892',
    projectId: 'ayokesituu',
    storageBucket: 'ayokesituu.appspot.com',
    iosBundleId: 'com.example.projectFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvZeotKIGgBTNxSURI4ZOXlpbfaSvpimk',
    appId: '1:983675880892:ios:de3311d77ea14bea47d7b9',
    messagingSenderId: '983675880892',
    projectId: 'ayokesituu',
    storageBucket: 'ayokesituu.appspot.com',
    iosBundleId: 'com.example.projectFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxdFvao4Bzv5ZdLDv5R6LQszwOyFIQCvk',
    appId: '1:983675880892:web:e331e7c0b3f9a84d47d7b9',
    messagingSenderId: '983675880892',
    projectId: 'ayokesituu',
    authDomain: 'ayokesituu.firebaseapp.com',
    storageBucket: 'ayokesituu.appspot.com',
    measurementId: 'G-NW1B8YW1TE',
  );
}
